apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: my-nginx
  namespace: flux-system
spec:
  interval: 1m
  path: ./apps/my-nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: Flux-gke-demo

