apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-gke-demo
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/gprashant2/Flux-gke-demo
  ref:
    branch: main
