apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: my-nginx
  namespace: default
spec:
  interval: 1m0s
  chart:
    spec:
      chart: ./charts/my-nginx
      sourceRef:
        kind: GitRepository
        name: flux-gke-demo
        namespace: flux-system
